### PR TITLE
#15/fix travis random fails

### LINKED ISSUE #15: Fix travis tests randomly failing
Sometimes the **handles the "showConfiguration" event if autoHandleEvents is not false** test fails with a timeout exceeded error.

### PR DESCRIPTION
**Pull request by keegan-lillo**
Resolves #15

### CODE REVIEW

File: test/spec/index.js [hunk 1]
```diff
@@ -58,10 +58,15 @@ describe('Clay', function() {
...
       var clay = fixture.clay([]);
+
+      // we stub the generateUrl method to avoid very large string comparisons.
+      var generateUrlStub = sinon.stub(clay, 'generateUrl');
+      generateUrlStub.returns('data:text/html;base64,PGh0bWw%2BVEVTVDwvaHRtbD4%3D');
       Pebble.addEventListener.withArgs('showConfiguration').callArg(1);
 
       assert(Pebble.addEventListener.calledWith('showConfiguration'));
       assert(Pebble.openURL.calledWith(clay.generateUrl()));
+      generateUrlStub.restore();
```
Comment (chapel) [inline test/spec/index.js]: In general it is not good to do any mocking/stubbing inside of your test conditions because if there is an error or assert failure, the mock/stub won't be restored and subsequent tests will fail as well. Also keep in mind that it could lead to inconsistent state between tests.

I've always manage the mock/stub creation and restoring in beforeEach and afterEach.

**Comment by chapel** [comment]
Only issue is the mock/stub behavior, up to you if you want to refactor that in or not.

File: test/spec/index.js (hunk 1 above)
Comment (keegan-lillo) [inline test/spec/index.js]: In this circumstance there are no side effects because `fixture.clay([]);` returns a new instance. I'm happy to leave it the way it is. I'll remember to do stubbing etc outside the test for things that do get recycled between tests.
